// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func underlineTabs() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_underlineTabs_322b`,
		Function: `function __templ_underlineTabs_322b(){document.addEventListener("DOMContentLoaded", function() {	
		const location = window.location.pathname 
		let element = document.getElementById("home")
		if (location == "/myMovies") {
			element = document.getElementById("myMoviesTab")
		} else if (location == "/browse") {
			element = document.getElementById("browseTab")
		} else if (location == "/login") {
			element = document.getElementById("loginTab")
		}
		element.classList.add("underline"); })
}`,
		Call:       templ.SafeScript(`__templ_underlineTabs_322b`),
		CallInline: templ.SafeScriptInline(`__templ_underlineTabs_322b`),
	}
}

func Layout(loggedIn bool) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link href=\"/public/output.css\" rel=\"stylesheet\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = underlineTabs().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"/public/htmx.min.js\"></script><title>Movies Diary</title></head><script>\n\t\tfunction closeModal(event) {\n\t\t\tevent.preventDefault()\n\t\t\tdocument.getElementById(\"add_modal_movie\").close()\n\t\t}\n\t\t</script><body class=\"\"><div class=\"mx-auto container min-h-screen\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Navbar(loggedIn).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><footer class=\"footer footer-center bg-base-200 mt-4 p-10 text-base-content rounded\"><div class=\"flex w-full items-center justify-between\"><aside><p>Copyright © 2024 - <br>This product uses the TMDB API but is not endorsed or certified by TMDB.</p></aside><div><p>Created By: Aziz Rmadi </p><nav><div class=\"flex items-center justify-center gap-4\"><a href=\"https://twitter.com/rmadiaziz1\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" class=\"fill-current\"><path d=\"M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z\"></path></svg></a> <a href=\"https://www.linkedin.com/in/ahmed-aziz-rmadi\"><img src=\"/public/linkedLogo.png\" class=\"w-[24px] h-[24px] text-base-content rounded-lg shadow-2xl\"></a></div></nav></div></div></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

// <footer class="footer footer-center absolute bottom-0 right-0 left-0 pt-4 text-base-content">
// 				<aside>
// 					<p>Copyright © 2024 - This product uses the TMDB API but is not endorsed or certified by TMDB.</p>
// 				</aside>
// 			</footer>
