// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"time"
)

type Movie struct {
	ID              int64
	UserID          int64
	Name            string
	WatchedDate     time.Time
	PosterUrl       string
	Diary           string
	Description     string
	LocationWatched string
	ReleaseDate     string
}

type User struct {
	ID    int64
	Name  string
	Email string
}
