name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11
      - run: npm install
      - name: update tailwindcss
        uses: ZoeyVid/tailwindcss-update@main
        with:
          input: css/input.css
          output: public/output.css
          params: "--minify"
      - name: Build
        run: go build -v -o moviesDiary
      - uses: actions/upload-artifact@v4
        with:
          name: binary-artifact
          path: |
            ./moviesDiary
            public/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: binary-artifact
      - name: Adding private SSH key to ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: scp binary to GCE and apply latest version
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp  -o StrictHostKeyChecking=no -r moviesDiary ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_SERVER }}:./moviesDiary.new
          scp  -o StrictHostKeyChecking=no -r public ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_SERVER }}:./publicNew
          ssh -o StrictHostKeyChecking=no ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_SERVER }} << 'ENDSSH'
            echo "** restarting service tof apply new version **"
            sudo service moviesDiary stop
            echo "** service stopped **"
            mv moviesDiary.new moviesDiary
            rm -rf public
            mv publicNew public
            chmod +x moviesDiary
            sudo service moviesDiary start
            echo "** service started **"
            ps -ef |grep moviesDiary
          ENDSSH
